### ISSUE TITLE
ValueError: need at least one array to concatenate

### ISSUE THREAD

**Issue by yang-china** [Jinbo-Hu/L3DAS22-TASK2#1]
Hi,Jinbo-Hu
I tried to reproduce the code,but ouccr this error.And the logs is here.
Dataset l3das22 is being developed......

Extracting scalar......

0it [00:02, ?it/s]
Traceback (most recent call last):
  File "code/main.py", line 77, in <module>
    sys.exit(main(args, cfg))
  File "code/main.py", line 51, in main
    preprocessor.extract_scalar()
  File "D:\sound source localization\L3DAS22-TASK2-master\code\learning\preprocess.py", line 271, in extract_scalar
    features_A = np.concatenate(features_A, axis=1)
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: need at least one array to concatenate

**Comment by Jinbo-Hu** [comment]
Can you check the shape of `batch_y_A`? I guess there is no sample in `batch_sample`, and you can also check `fn_list` in code/methods/data.py.
